[project]
name = "internvl3-5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "decord>=0.6.0",
    "lmdeploy>=0.10.1",
    "timm>=1.0.20",
]
